name: patrol_management_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  video_thumbnail: ^0.5.3
  video_player: ^2.7.0
  flutter_svg: ^2.0.17
  crypto: ^3.0.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.14
  shared_preferences: ^2.5.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env
    - assets/svg/google_logo.svg
    - assets/svg/x_logo.svg
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/kor/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/kor/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/kor/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/kor/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/kor/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/kor/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/kor/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/kor/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/kor/NotoSansKR-Black.ttf
          weight: 900

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_28pt-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter_28pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_28pt-Medium.ttf
          weight: 500