name: muniverse_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  video_thumbnail: ^0.5.3
  video_player: ^2.7.0
  flutter_svg: ^2.0.17
  crypto: ^3.0.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.14
  shared_preferences: ^2.5.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.4
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  google_sign_in: ^6.3.0
  url_launcher: ^6.2.5
  twitter_login: ^4.4.2
  flutter_html: ^3.0.0
  uni_links: ^0.5.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env
    - assets/svg/google_logo.svg
    - assets/svg/x_logo.svg
    - assets/svg/m_logo.svg
    - assets/svg/Muniverse.svg
    - assets/svg/scroll_top.svg
    - assets/images/
    - assets/images/artist/
    - assets/images/vote/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900