import '../../models/event/event_model.dart';
import '../../models/artist_model.dart'; // 아티스트 더미 데이터용

final List<EventModel> eventList = [
  EventModel(
    eventCode: 'EVT001',
    name: '2025 MOKPO MUSICPLAY',
    content: '목포 뮤직플레이',
    status: 'ACTIVE',
    bannerUrl: 'assets/images/banner_mokpo.png',
    profileUrl: 'assets/images/event_description_bof.png',
    preOpenDateTime: DateTime(2025, 7, 1),
    openDateTime: DateTime(2025, 7, 15),
    endDateTime: DateTime(2025, 7, 18),
    performanceStartTime: DateTime(2025, 7, 15, 18, 0),
    performanceEndTime: DateTime(2025, 7, 18, 22, 0),
    activeFlag: true,
    createDate: DateTime(2025, 6, 1),
    updateDate: null,
    deleteFlag: false,
    artists: [
      ArtistModel(
        artistCode: 'ART001',
        name: '르세라핌',
        content: 'K-POP 걸그룹',
        profileUrl: 'assets/images/lesserafim.png',
        artistType: 'GIRL_GROUP',
        createDate: DateTime(2025, 1, 1),
        updateDate: null,
        deleteFlag: false,
      ),
    ],
  ),
  EventModel(
    eventCode: 'EVT002',
    name: 'BUSAN ONE ASIA FESTIVAL',
    content: '부산 원아시아 페스티벌',
    status: 'ACTIVE',
    bannerUrl: 'assets/images/banner_bof.png',
    profileUrl: 'assets/images/event_description_bof.png',
    preOpenDateTime: DateTime(2025, 8, 20),
    openDateTime: DateTime(2025, 9, 10),
    endDateTime: DateTime(2025, 9, 13),
    performanceStartTime: DateTime(2025, 9, 10, 17, 0),
    performanceEndTime: DateTime(2025, 9, 13, 21, 0),
    activeFlag: true,
    createDate: DateTime(2025, 6, 15),
    updateDate: null,
    deleteFlag: false,
    artists: [
      ArtistModel(
        artistCode: 'ART002',
        name: '더킹덤',
        content: 'K-POP 보이그룹',
        profileUrl: 'assets/images/thekingdom.png',
        artistType: 'BOY_GROUP',
        createDate: DateTime(2025, 2, 1),
        updateDate: null,
        deleteFlag: false,
      ),
    ],
  ),
];
